name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "feature" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Download the lambda
      run: go get github.com/aws/aws-lambda-go/lambda
      
    - name: Go Build
      run: |
        #CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -a -o main main.go
      
    - name: artifact gen
      run: zip deployment.zip main
      
    - name: deploy
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}       
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
         
    - name: Zip file
      run: aws lambda update-function-code --function-name ${{ secrets.AWS_FUNCTION_NAME }} --zip-file fileb://deployment.zip 
      
  notify-team-start:
    runs-on: ubuntu-latest
    steps:
      - name: Team Notify Start
        uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          deploy-card: true
          title: 'Deployment Started'
          color: 'info'
#         uses: simbo/msteams-message-card-action@v1
#         with:
#           github-token: ${{ github.token }}
#           webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
#           title: Started!
#           message:  "BTMS `${{ inputs.ref }}` build (${{ github.actor }}): Started..."
#           color: 28a745

  notify-team-success:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Team Notify of Success
        uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          deploy-card: true
          title: 'Deployment Successful'
          color: 'success'
#         uses: simbo/msteams-message-card-action@v1
#         with:
#           github-token: ${{ github.token }}
#           webhook: ${{ secrets.MS_TEAMS_WEBHOOK_URI }} 
#           title: Success!
#           message: "BTMS `${{ inputs.ref }}` build (${{ github.actor }}) completed successfully. Image was pushed to ECR and is available to be deployed. :white_check_mark:"
#           color: 33ff66

  notify-team-failure:
    if: failure()
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Team Notify of Failure
        uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          deploy-card: true
          title: 'Deployment Failed'
          color: 'failure'
