# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Download the lambda
      run: go get github.com/aws/aws-lambda-go/lambda
        
    - name: Set Up Env Variables
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64
      
    - name: Verify Env Variables
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -a -o main main.go
      
    - name: list directory
      run: ls
      
    - name: artifact gen
      run: zip deployment.zip main
      
    - name: list directory post build
      run: ls
      
    - name: deploy
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}       
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
    - name: Zip file
      run: aws lambda update-function-code --function-name POC-lamda --zip-file fileb://deployment.zip 
