name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "feature" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Download the lambda
      run: go get github.com/aws/aws-lambda-go/lambda
      
    - name: Go Build
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -a -o main main.go
      
    - name: artifact gen
      run: zip deployment.zip main
      
    - name: deploy
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}       
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
         
    - name: Zip file
      run: aws lambda update-function-code --function-name ${{ secrets.AWS_FUNCTION_NAME }} --zip-file fileb://deployment.zip 
      
      
  notify-team-success:
    runs-on: ubuntu-latest
    steps:
      - name: Team Notify of Success
        uses: toko-bifrost/ms-teams-deploy-card@3.1.2
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          timezone: US/Eastern    
  notify-team-failure:
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Team Notify of Failure
        uses: toko-bifrost/ms-teams-deploy-card@3.1.2
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          timezone: US/Eastern
