name: Docker Image CI 

on: 
  push: 
    branches: [ "main" ] #"dev", "release/*" ] 

jobs:

  code_coverage:

    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Go Version
      run: go version
        
    - name: Go build
      run: go build
      
    - name: List Directory
      run: ls
      
    - name: Go test 
      run: go test

  Dev_Image_Build: 
  
    needs: code_coverage
    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@v3 
    - name: Read VERSION file 
      id: getversion 
      run: echo "version=$(cat app-version)" >> $GITHUB_OUTPUT 
    - name: Checking
      run: echo "The version is ${{ steps.getversion.outputs.version }}"
   
